fix MultiStrategyDispatch to work with new GenConverter and attrs inheritance
Tinche/cattrs pull request #117
Opened 2021-01-24 04:09 UTC by petergaultney

Because the GenConverter specifically handles generating code for
attrs classes, and because it registers hooks that don't require
function dispatch, singledispatch was preventing subclasses from
having code generated for them, because they would trigger the
previously-generated base class's structure/unstructure code.

This changes MultiStrategyDispatch to allow for a class-based hook to
specifically avoid single-dispatch. Since we know that a given attrs
class can always have code generated for it, we don't really want to
share dispatch across subclasses - like the original Converter, we
want to make sure we're structuring each individual attrs class as its
own separate type.

fixes #116

2021-01-24 22:59 UTC, Tinche requested changes
Please add a HISTORY entry with a link to the PR and issue and I'll merge this in :)

2021-01-24 22:59 UTC, Tinche commented on src/cattr/multistrategy_dispatch.py
> +        self._direct_dispatch = dict()
```suggestion
        self._direct_dispatch = {}
```
For consistency

2021-01-24 22:59 UTC, Tinche commented on src/cattr/multistrategy_dispatch.py
> +            if direct_dispatch:
```suggestion
            if direct_dispatch is not None:
```

2021-01-24 23:00 UTC, Tinche commented on src/cattr/multistrategy_dispatch.py
> +            if direct_dispatch:
```suggestion
            if direct_dispatch is not None:
```

2021-01-25 02:51 UTC, petergaultney commented
i put the entry in 1.2.0 but if you decide to do a bugfix release first, let me know and I can change it to a 1.1.3.

2021-01-25 12:07 UTC, Tinche approved these changes
Thanks for this. I might add a few tests and then release this as 1.2.0 in a few days.

2021-01-25 12:07 UTC, merged

2021-01-28 12:02 UTC, Tinche commented
I had to tweak this a little so that direct dispatch is consulted after the singledispatch, not before, to get some tests to pass.